### ISSUE TITLE
`tests` folder not checked into repo

### ISSUE THREAD

**Issue by beardedtim** [LanceJernigan/Nightwatch-Boilerplate#1]
According to the `README`:

> Simply add your tests to the /tests/ folder in the root of this boilerplate and run yarn test. Nightwatch will run all the tests within the /tests/ folder and output the results in the console.

However, since either the `tests/` dir did not get checked in or it was empty when getting pushed, it is not included in this repo. Does that mean that the end user needs to create it and follow the naming convention of `tests/`?

**Comment by LanceJernigan** [comment]
Just added a `tests/` dir with an example test.
